import {
  Utensils,
  Car,
  Home,
  Zap,
  Gamepad2,
  HeartPulse,
  Shirt,
  BookOpen,
  PawPrint,
  Gift,
  Banknote,
  Laptop,
  ShoppingBag,
  TrendingUp,
  CircleEllipsis,
  Plane,
  Dumbbell,
  Coffee,
  Music,
  Smartphone,
  Baby,
  Wrench,
  Briefcase,
  PiggyBank,
  CreditCard,
  Bus,
  Bike,
  Beer,
  Pill,
  GraduationCap,
  CirclePlus,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  home: Home,
  zap: Zap,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  shirt: Shirt,
  "book-open": BookOpen,
  "paw-print": PawPrint,
  gift: Gift,
  banknote: Banknote,
  laptop: Laptop,
  "shopping-bag": ShoppingBag,
  "trending-up": TrendingUp,
  plane: Plane,
  dumbbell: Dumbbell,
  coffee: Coffee,
  music: Music,
  smartphone: Smartphone,
  baby: Baby,
  wrench: Wrench,
  briefcase: Briefcase,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  bus: Bus,
  bike: Bike,
  beer: Beer,
  pill: Pill,
  "graduation-cap": GraduationCap,
  "circle-plus": CirclePlus,
  "circle-ellipsis": CircleEllipsis,
  wallet: Wallet,
};

export const ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string | null): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || CircleEllipsis;
}

export { CircleEllipsis };
